/* SPDX-License-Identifier: LGPL-2.1-or-later */

/* systemd-yaml-generator — because INI was mass adopted in the 1980s and it's mass adopted today, but YAML
 * is the configuration format for the 21st century. */

#include <ctype.h>
#include <dirent.h>
#include <errno.h>
#include <stdio.h>

#include "alloc-util.h"
#include "dirent-util.h"
#include "fd-util.h"
#include "fileio.h"
#include "generator.h"
#include "log.h"
#include "path-util.h"
#include "string-util.h"

static const char *arg_dest = NULL;

/* A deliberately minimal YAML-ish parser.
 *
 * Supports exactly the subset of YAML needed for systemd unit files:
 *   - Top-level keys become [Section] headers
 *   - Indented key: value pairs become Key=Value lines
 *   - Lists (- item) become repeated Key=item lines
 *   - Everything else is a parse error, as nature intended
 */

typedef struct YamlLine {
        size_t indent;
        char *key;     /* NULL for list items */
        char *value;   /* NULL for section-only lines */
        bool is_list_item;
} YamlLine;

static void yaml_line_done(YamlLine *line) {
        if (!line)
                return;
        free(line->key);
        free(line->value);
}

/* Count leading spaces. Tabs are a YAML crime. */
static size_t count_indent(const char *s) {
        size_t n = 0;

        while (s[n] == ' ')
                n++;

        return n;
}

static int parse_yaml_line(const char *raw, YamlLine *ret) {
        const char *p;
        size_t indent;

        assert(raw);
        assert(ret);

        *ret = (YamlLine) {};

        indent = count_indent(raw);
        p = raw + indent;

        /* Skip empty lines and comments */
        if (isempty(p) || *p == '#') {
                *ret = (YamlLine) { .indent = indent };
                return 0; /* skip */
        }

        if (strchr(raw, '\t'))
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                       "Tabs detected in YAML. Even YAML knows tabs are wrong.");

        /* List item: "- value" */
        if (startswith(p, "- ")) {
                p += 2;
                while (*p == ' ')
                        p++;

                ret->indent = indent;
                ret->value = strdup(p);
                if (!ret->value)
                        return log_oom();

                ret->is_list_item = true;
                return 1;
        }

        /* Key: value or Key: (section header) */
        const char *colon = strchr(p, ':');
        if (!colon)
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                       "Line is neither a key:value pair nor a list item.: %s", raw);

        ret->indent = indent;
        ret->key = strndup(p, colon - p);
        if (!ret->key)
                return log_oom();

        /* Value after colon */
        p = colon + 1;
        while (*p == ' ')
                p++;

        if (!isempty(p)) {
                ret->value = strdup(p);
                if (!ret->value)
                        return log_oom();
        }

        return 1;
}

static int convert_yaml_to_unit(const char *yaml_path, const char *unit_name) {
        _cleanup_free_ char *contents = NULL;
        _cleanup_fclose_ FILE *f = NULL;
        _cleanup_free_ char *current_section = NULL;
        _cleanup_free_ char *current_list_key = NULL;
        int r;

        assert(yaml_path);
        assert(unit_name);

        r = read_full_file(yaml_path, &contents, NULL);
        if (r < 0)
                return log_error_errno(r, "Failed to read YAML file %s: %m", yaml_path);

        r = generator_open_unit_file(arg_dest, yaml_path, unit_name, &f);
        if (r < 0)
                return r;

        fprintf(f, "# Automatically generated by systemd-yaml-generator(8) from %s\n"
                   "# This unit was bravely converted from YAML.\n\n",
                yaml_path);

        for (const char *line = contents;;) {
                _cleanup_(yaml_line_done) YamlLine yl = {};
                const char *eol;

                eol = strchr(line, '\n');
                if (!eol && isempty(line))
                        break;

                _cleanup_free_ char *current_line = NULL;
                if (eol) {
                        current_line = strndup(line, eol - line);
                        line = eol + 1;
                } else {
                        current_line = strdup(line);
                        line += strlen(line);
                }
                if (!current_line)
                        return log_oom();

                /* Strip trailing whitespace */
                delete_trailing_chars(current_line, WHITESPACE);

                r = parse_yaml_line(current_line, &yl);
                if (r < 0)
                        return r;
                if (r == 0)
                        continue; /* empty/comment */

                if (yl.is_list_item) {
                        /* List item — repeat previous key */
                        if (!current_list_key)
                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                                       "List item without preceding key in %s", yaml_path);

                        fprintf(f, "%s=%s\n", current_list_key, yl.value);
                        continue;
                }

                if (yl.indent == 0 && !yl.value) {
                        /* Top-level key with no value = section header */
                        fprintf(f, "\n[%s]\n", yl.key);

                        free_and_replace(current_section, yl.key);
                        current_list_key = mfree(current_list_key);
                        continue;
                }

                if (yl.indent == 0 && yl.value) {
                        /* Top-level key with value — treat as section header + first entry? */
                        return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                               "Top-level key '%s' has a value. "
                                               "Section headers must not have values. "
                                               "Did you mean to indent this?", yl.key);
                }

                if (yl.indent > 0 && yl.value) {
                        /* Indented key: value pair */
                        if (!current_section)
                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                                       "Key '%s' is not inside a section in %s",
                                                       yl.key, yaml_path);

                        fprintf(f, "%s=%s\n", yl.key, yl.value);

                        /* Remember key for potential list continuation */
                        r = free_and_strdup(&current_list_key, yl.key);
                        if (r < 0)
                                return log_oom();
                        continue;
                }

                if (yl.indent > 0 && !yl.value) {
                        /* Indented key with no value — upcoming list */
                        if (!current_section)
                                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                                       "Key '%s' is not inside a section in %s",
                                                       yl.key, yaml_path);

                        r = free_and_strdup(&current_list_key, yl.key);
                        if (r < 0)
                                return log_oom();
                        continue;
                }
        }

        r = fflush_and_check(f);
        if (r < 0)
                return log_error_errno(r, "Failed to write unit file %s: %m", unit_name);

        log_info("Successfully converted %s to %s. YAML superiority achieved.", yaml_path, unit_name);
        return 0;
}

static int determine_unit_name(const char *yaml_filename, char **ret) {
        /* my-service.service.yml -> my-service.service
         * my-timer.timer.yml    -> my-timer.timer
         * etc. */
        const char *e;

        assert(yaml_filename);
        assert(ret);

        e = endswith(yaml_filename, ".yml");
        if (!e)
                e = endswith(yaml_filename, ".yaml");
        if (!e)
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                       "File %s does not have .yml or .yaml extension.",
                                       yaml_filename);

        _cleanup_free_ char *unit_name = strndup(yaml_filename, e - yaml_filename);
        if (!unit_name)
                return log_oom();

        /* Verify that the remaining name has a valid unit suffix */
        static const char *valid_suffixes[] = {
                ".service", ".socket", ".device", ".mount", ".automount",
                ".swap", ".target", ".path", ".timer", ".slice", ".scope",
        };

        bool valid = false;
        FOREACH_ELEMENT(suffix, valid_suffixes) {
                if (endswith(unit_name, *suffix)) {
                        valid = true;
                        break;
                }
        }

        if (!valid)
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                       "File %s does not contain a valid unit type suffix ",
                                       yaml_filename);

        *ret = TAKE_PTR(unit_name);
        return 0;
}

static int scan_dir_for_yaml(const char *path) {
        _cleanup_closedir_ DIR *d = NULL;
        int r;

        d = opendir(path);
        if (!d) {
                if (errno == ENOENT)
                        return 0;
                return log_error_errno(errno, "Failed to open directory %s: %m", path);
        }

        FOREACH_DIRENT(de, d, return -errno) {
                _cleanup_free_ char *yaml_path = NULL, *unit_name = NULL;

                if (!endswith(de->d_name, ".yml") && !endswith(de->d_name, ".yaml"))
                        continue;

                r = determine_unit_name(de->d_name, &unit_name);
                if (r < 0) {
                        log_warning_errno(r, "Skipping %s/%s: %m", path, de->d_name);
                        continue;
                }

                yaml_path = path_join(path, de->d_name);
                if (!yaml_path)
                        return log_oom();

                r = convert_yaml_to_unit(yaml_path, unit_name);
                if (r < 0)
                        log_warning_errno(r, "Failed to convert %s, skipping: %m", yaml_path);
        }

        return 0;
}

static int run(const char *dest, const char *dest_early, const char *dest_late) {
        int r;

        assert_se(arg_dest = dest);

        /* Scan standard unit file directories for YAML files. */
        static const char *search_paths[] = {
                "/etc/systemd/system",
                "/run/systemd/system",
                "/usr/local/lib/systemd/system",
                "/usr/lib/systemd/system",
        };

        FOREACH_ELEMENT(path, search_paths) {
                r = scan_dir_for_yaml(*path);
                if (r < 0)
                        log_warning_errno(r, "Failed to scan %s for YAML files, ignoring: %m", *path);
        }

        return 0;
}

DEFINE_MAIN_GENERATOR_FUNCTION(run);
