---
# SPDX-License-Identifier: LGPL-2.1-or-later
name: build-stats

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-stats:
    runs-on: ubuntu-24.04
    # if: github.repository == 'systemd/systemd'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: systemd/mkosi@71d7b67e01dc47ab5c51f24866c3e2195b9701d2

      # Freeing up disk space with rm -rf can take multiple minutes. Since we don't need the extra free space
      # immediately, we remove the files in the background. However, we first move them to a different location
      # so that nothing tries to use anything in these directories anymore while we're busy deleting them.
      - name: Free disk space
        run: |
          sudo mv /usr/local /usr/local.trash
          sudo mv /opt/hostedtoolcache /opt/hostedtoolcache.trash
          sudo systemd-run rm -rf /usr/local.trash /opt/hostedtoolcache.trash

      - name: Configure
        run: |
          tee mkosi/mkosi.local.conf <<EOF
          [Distribution]
          Distribution=arch

          [Build]
          ToolsTreeDistribution=arch
          WithTests=no

          [Runtime]
          RAM=4G
          EOF

      - name: Show image summary
        run: mkosi summary

      - name: Build tools tree
        run: sudo mkosi -f box -- true

      - name: Configure meson
        run: |
          sudo mkosi box -- \
            meson setup \
            build

      - name: Build systemd
        run: sudo mkosi box -- meson compile -C build

      - name: Collect stats
        run: mkosi box -- ./tools/binary-sizes.py build
